version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_OPTIONS=--max_old_space_size=1024
    command: ["npm", "run", "dev"]
    deploy:
      resources:
        limits:
          memory: 512M

  backend:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/storedb
    depends_on:
      - mongodb
    command: ["npm", "run", "dev"]
    deploy:
      resources:
        limits:
          memory: 512M

  backend-copy:
    build: ./backend
    ports:
      - "5002:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/storedb
    depends_on:
      - mongodb
    command: ["npm", "run", "dev"]
    deploy:
      resources:
        limits:
          memory: 512M

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    deploy:
      resources:
        limits:
          memory: 512M

  load-balancer:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
      - backend-copy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          memory: 512M
